IP_SERVER="192.168.56.110"
IP_WORKER="192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"

  config.vm.provider "virtualbox" do |lv|
    lv.cpus = "1"
    lv.memory = "1024"
  end

  config.vm.define "hsharameS" do |server|
    server.vm.hostname = "hsharameS"
    server.vm.network :private_network, ip: IP_SERVER
    server.vm.provision "shell", path: "scripts/k3s_server.sh",
      env: { "IP_SERVER" => IP_SERVER }
  end

  config.vm.define "hsharameSW" do |worker|
    worker.vm.hostname = "hsharameSW"
    worker.vm.network :private_network, ip: IP_WORKER
    worker.vm.provision "shell", path: "scripts/k3s_agent.sh",
      env: { "K3S_SERVER_IP" => IP_SERVER }
  end
end
