# Vagrant.configure(2) do |config|
#   [...]
#   config.vm.box = REDACTED
#   config.vm.box_url = REDACTED
#   config.vm.define "wilS" do |control|
  #   control.vm.hostname = "wilS"
  #   control.vm.network REDACTED, ip: "192.168.56.110"
  #   control.vm.provider REDACTED do |v|
  #   v.customize ["modifyvm", :id, "--name", "wilS"]
  #   [...]
  #   end
  #   config.vm.provision :shell, :inline => SHELL
    #   [...]
  #   SHELL
    #   control.vm.provision "shell", path: REDACTED
#   end
#   config.vm.define "wilSW" do |control|
  #   control.vm.hostname = "wilSW"
  #   control.vm.network REDACTED, ip: "192.168.56.111"
  #   control.vm.provider REDACTED do |v|
  #   v.customize ["modifyvm", :id, "--name", "wilSW"]
  #   [...]
  #   end
  #   config.vm.provision "shell", inline: <<-SHELL
  #   [..]
  #   SHELL
  #   control.vm.provision "shell", path: REDACTED
  #   end
#   end

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"


  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "512"
  end

  config.vm.define "hsharameS" do |host1|
    host1.vm.hostname = "hsharameS"
    host1.vm.network :private_network, ip: "192.168.56.110"
  end

  config.vm.define "hsharameSW" do |host2|
    host2.vm.hostname = "hsharameSW"
    host2.vm.network :private_network, ip: "192.168.56.111"
  end
end


  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
