Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"


  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "512"
  end

  config.vm.define "hsharameS" do |host1|
    host1.vm.hostname = "hsharameS"
    host1.vm.network :private_network, ip: "192.168.56.110"
    host1.vm.provision "shell", path: "scripts/kubectl_inst.sh"
    host1.vm.provision "shell", path: "scripts/k3s_server.sh"
  end

  config.vm.define "hsharameSW" do |host2|
    host2.vm.hostname = "hsharameSW"
    host2.vm.network :private_network, ip: "192.168.56.111"
    host2.vm.provision "shell", path: "scripts/kubectl_inst.sh"
    host2.vm.provision "shell", path: "scripts/k3s_agent.sh"
  end
end
