apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  labels:
    app: two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
    spec:
      containers:
      - name: app-two
        image: nginx:stable-trixie-perl
        command:
          - sh
          - -c
          - |
            echo "Hello from app2" > /usr/share/nginx/html/index.html
            nginx -g "daemon off;"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  type: ClusterIP
  selector:
    app: two
  ports:
  - port: 80
    protocol: TCP
